// import resource 
import emblem from './components/img/emblem.svg'
import GooglePlay from './components/img/googleplay.svg'
import AppStore from './components/img/app store.svg'
import logoFB from './components/img/Facebook.svg'
import logoFixed from './components/img/fixed org.svg'
import logoKonsul from './components/img/org konsul.svg'
import logoServis from './components/img/org servis.svg'
import logoAkun from './components/img/works_account.svg'
import logoAman from './components/img/works_secure.svg'
import logoEnjoy from './components/img/works_smile.svg'
import logoTesti from './components/img/testimoni.svg'
import logoFooter from './components/img/logo footer.svg'
import logoTW from './components/img/Twitter.svg'
import logoIG from './components/img/Instagram.svg'
import logoJumboHP from './components/img/jumbo_hp.svg'